version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_usuarios
    volumes:
      - ./esquema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
